"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class file_recv_lcmt(object):

    __slots__ = ["result"]

    __typenames__ = ["int8_t"]

    __dimensions__ = [None]

    def __init__(self):
        self.result = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(file_recv_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.result))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != file_recv_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return file_recv_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = file_recv_lcmt()
        self.result = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if file_recv_lcmt in parents: return 0
        tmphash = (0xf676533f1f6d36be) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if file_recv_lcmt._packed_fingerprint is None:
            file_recv_lcmt._packed_fingerprint = struct.pack(">Q", file_recv_lcmt._get_hash_recursive([]))
        return file_recv_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", file_recv_lcmt._get_packed_fingerprint())[0]

